# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "FXTrade_VM1" ]
  pull_request:
    branches: [ "FXTrade_VM1" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build and Push Docker Image PartyA
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: wfsettlement/fxtrade-vm1
        tags: PartyA     
        dockerfile: ./Dockerfile_PartyA        
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image PartyB
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: wfsettlement/fxtrade-vm1
        tags: PartyB
        dockerfile: ./Dockerfile_PartyB        
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image PartyC
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: wfsettlement/fxtrade-vm1
        tags: PartyC
        dockerfile: ./Dockerfile_PartyC        
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push Docker Image Notary
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: wfsettlement/fxtrade-vm1
        tags: Notary
        dockerfile: ./Dockerfile_Notary
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}        

    - name: Start Deployment
      uses: TapTap21/docker-remote-deployment-action@v1.0
      with:
        remote_docker_host: ${{ secrets.AZ_VM_IP }}
        ssh_private_key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.VM_SSH_PUBLIC_KEY }}
        stack_file_name: docker-compose.yml
        docker_login_password: ${{ secrets.DOCKER_PASSWORD }}
        docker_login_user: ${{ secrets.DOCKER_USERNAME }}
        docker_login_registry : docker.io
        args: -p myapp up -d
        
    - name: Deploy to Azure VM1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZ_VM_IP }}
        username: ${{ secrets.AZ_VM_USERNAME }}
        key: ${{ secrets.VM_SSH_PRIVATE_KEY}}
        port: 22
        script: |
          eval "$(ssh-agent)"
          ssh-add - <<<"${{ secrets.VM_SSH_PRIVATE_KEY }}"
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker-compose up -d
